/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Options for [`get_frames`]. Everything optional; effect-specific knobs
 * travel in `effect_args` as CLI flags (e.g. `["--typing-speed", "5"]`).
 */
export interface FramesOptions {
  seed?: number
  frameRate?: number
  canvasWidth?: number
  canvasHeight?: number
  tabWidth?: number
  wrapText?: boolean
  noColor?: boolean
  xtermColors?: boolean
  maxFrames?: number
  randomEffect?: boolean
  includeEffects?: Array<string>
  excludeEffects?: Array<string>
  effectArgs?: Array<string>
}
/** Names of all 37 effects, in registry order. */
export declare function listEffects(): Array<string>
/**
 * Render an effect headlessly: every frame as an ANSI string, top row first.
 *
 * Deterministic for a given seed (virtual clock — wall time never consulted).
 * The canvas is input-sized unless `canvas_width`/`canvas_height` fix it;
 * terminal dimensions are never read, so output is machine-independent.
 */
export declare function getFrames(input: string, effect: string, options?: FramesOptions | undefined | null): Array<string>
